# This file was generated by GoReleaser. DO NOT EDIT.
cask "compagnie" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "6c1d51769976432c2234b0be90bc2819b50c79c1075a317c3eac9abda60cefcd"
      url "https://github.com/ekklosaas/compagnie-cli/releases/download/v#{version}/compagnie_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f46f15ae343b8bdc9d54665c059907a275538fa70bddebd1620c047caf74b73"
      url "https://github.com/ekklosaas/compagnie-cli/releases/download/v#{version}/compagnie_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "187525a543188d039ead7dc5504e088445470f2cb277fb162bd83673a8aa1bcd"
      url "https://github.com/ekklosaas/compagnie-cli/releases/download/v#{version}/compagnie_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a712560263fd3ca74870049a88db0709b5519b2b07933066933fc1b110e58412"
      url "https://github.com/ekklosaas/compagnie-cli/releases/download/v#{version}/compagnie_#{version}_linux_arm64.tar.gz"
    end
  end

  name "compagnie"
  desc "Compagnie — the Company OS, from your terminal"
  homepage "https://compagnie.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compagnie"

  # No zap stanza required

end
