# This file was generated by GoReleaser. DO NOT EDIT.
cask "compagnie" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "f47661337e597a9184ca5a93c52626cc3fe506cb4d4631ba15fa7c232c0bcba5"
      url "https://github.com/ekklosaas/Compagnie/releases/download/v#{version}/compagnie_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c693dcce1ecdef54d9cde961357150064c529531075fce363f6649bd5c8f4346"
      url "https://github.com/ekklosaas/Compagnie/releases/download/v#{version}/compagnie_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d9dd1abf5f1710be2eb31f5a0c94d60dbffa5b051f66c616b068166d44580a4"
      url "https://github.com/ekklosaas/Compagnie/releases/download/v#{version}/compagnie_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a48229f5c4e17c859bedee6c143a4d2f7891c8e9a7cce4a0b4d4c00c95049318"
      url "https://github.com/ekklosaas/Compagnie/releases/download/v#{version}/compagnie_#{version}_linux_arm64.tar.gz"
    end
  end

  name "compagnie"
  desc "Compagnie — the Company OS, from your terminal"
  homepage "https://compagnie.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compagnie"

  # No zap stanza required

end
