# This file was generated by GoReleaser. DO NOT EDIT.
cask "compagnie" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0e21e690ce2b5c5c13f98383a75c9414178fb8f4c66e50eb58b09b99cf94b034"
      url "https://github.com/ekklosaas/Compagnie/releases/download/v#{version}/compagnie_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4cd01ebcd570c6173d83130676d2b455d6d9c083067a3eac17ec547d48524285"
      url "https://github.com/ekklosaas/Compagnie/releases/download/v#{version}/compagnie_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e81cfb8cef93d2fdba1b3eb2bf06236a4154bb4193d0aa9e7a48c9060c204cd0"
      url "https://github.com/ekklosaas/Compagnie/releases/download/v#{version}/compagnie_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec0491e21dfac2ad7560b0488f08d5e996c62f312f5f48a85758f3b581cf7129"
      url "https://github.com/ekklosaas/Compagnie/releases/download/v#{version}/compagnie_#{version}_linux_arm64.tar.gz"
    end
  end

  name "compagnie"
  desc "Compagnie — the Company OS, from your terminal"
  homepage "https://compagnie.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compagnie"

  # No zap stanza required

end
